# Generated by Django 3.2.7 on 2021-09-11 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('species', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='animal',
            name='description',
            field=models.CharField(default='none', max_length=1000),
        ),
        migrations.AlterField(
            model_name='animal',
            name='image_url',
            field=models.CharField(default='none', max_length=200),
        ),
        migrations.AlterField(
            model_name='animal',
            name='latin_name',
            field=models.CharField(default='none', max_length=200),
        ),
        migrations.AlterField(
            model_name='animal',
            name='status',
            field=models.CharField(default='none', max_length=200),
        ),
    ]
